gText_Birch_Welcome:: @ 82C897B
	.string "Χαῖρε! σύγγνωθί μοι τὸ σε περιμένειν!\p"
	.string "ἀσπάζομαι εἰς τὴν γὴν τοῦ POKéMON!\p"
	.string "τοὔνομά μου BIRCH.\p"
	.string "ἀλλὰ πάντες με ὀνομάζουσι τὸν ΔΙΔΑΣΚΑΛΟΝ\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Modifying this doesn't actually modify “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Αὕτη γὴ πολλὰ οἰκουμένη ἐστίν\n"
	.string "ὑπὸ θηρίων ὀνομαζομένων POKéMON.\p"
	.string "ἄνθρωποι ζῶμεν παρὰ POKéMON,\n"
	.string "ὡς μὲν παίγνια φιλά,\l"
	.string "ὡς δὲ συνεργάτας κοινούς.\p"
	.string "ἐνίοτε δὲ συνερχόμεθα\n"
	.string "καὶ μαχόμεθα ἄλλους ὡς ἡμᾶς.\p"
	.string "καίπερ ἔχομεν φιλίαν μεγάλην μέτ'\n"
	.string "POKéMON, οὐκ οἴδαμεν πάντα τὰ περὶ\l"
	.string "αὐτῶν.\p"
	.string "πλεῖστα κρύπτα ἐστίν περὶ\n"
	.string "POKéMON.\p"
	.string "ἀποκαλυφθῆναι ταῦτα, \n"
	.string "ἐπικεχείρηκα ζήτησιν.\l"
	.string "τοῦτο ὃ ποιῶ.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
